development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:f3840900e70229776df91ba7384d4e4b@dory.redistogo.com:9930/
  channel_prefix: message_me_production
